language: java
notifications:
  email:
    - matthias@thinkaurelius.com
    - marko@thinkaurelius.com
    - dalaro@hopcount.org
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  only:
    - master
